### ISSUE TITLE
How to do ORB sparse sampling？

### ISSUE THREAD

**Issue by 619862306** [choyingw/CFCNet#1]
Thanks for your work！
As shown in paper，there are three strategys of sampling the dense/semi-dense depth maps. I read your code and understand two of them(Uniform & Stereo), but the ORB Sparsifier is not shown in the code. Could you tell me how to do it?

**Comment by choyingw** [comment]
@619862306 Sorry for the late reply. We will release the ORB sparsifier codes along with pretrained models recently.

**Comment by longyangqi** [comment]
Awesome work!
Looking forward to the ORB sparsifier.

**Comment by choyingw** [comment]
@longyangqi Sorry for waiting. We have posted the update on the repo.
