### ISSUE TITLE
train NYUDataset error

### ISSUE THREAD

**Issue by QiuJunning** [choyingw/CFCNet#6]
Hello,I tried to run your train_depth_complete.py but an error occurred. I run the code on Windows system,and I set num_threads to 0 and I set path in options.py.

  As a beginner, I don't know whether it is caused by not running on Linux system or not setting the running parameters correctly. I hope you can help me find out the problem. Thank you very much.Here are the results of my run

D:\Anaconda\envs\pytorch\python.exe D:/科研资料/CCA/CFCNet-master/train_depth_complete.py
----------------- Options ---------------
               batch_size: 16                            
          checkpoints_dir: ./checkpoints                 
           continue_train: False                         
                    epoch: latest                        
              epoch_count: 1                             
                  gpu_ids: 0                             
                init_gain: 0.02                          
                init_type: xavier                        
                  isTrain: True                          	[default: None]
                lambda_L1: 100.0                         
                       lr: 0.001                         
          lr_decay_epochs: 100                           
           lr_decay_iters: 5000000                       
                 lr_gamma: 0.9                           
                lr_policy: lambda                        
         max_dataset_size: inf                           
                    model: DCCA_sparse                   
                 momentum: 0.9                           
                       nP: 500                           
                     name: experiment_name               
                    niter: 400                           
                  no_flip: True                          
                     norm: instance                      
              num_threads: 0                             
                    phase: train                         
               print_freq: 1                             
           resize_or_crop: none                          
          save_epoch_freq: 1                             
                     seed: 0                             
           serial_batches: False                         
                   suffix:                               
                test_path: D:/科研资料/CCA/CFCNet-master/nyudepthv2/val/
               train_path: D:/科研资料/CCA/CFCNet-master/nyudepthv2/train/
                  verbose: False                         
             weight_decay: 0.0005                        
----------------- End -------------------
Found 47584 images in train folder.
Found 654 images in val folder.
----------------- Options ---------------
               batch_size: 16                            
          checkpoints_dir: ./checkpoints                 
           continue_train: False                         
                    epoch: latest                        
              epoch_count: 1                             
                  gpu_ids: 0                             
                init_gain: 0.02                          
                init_type: xavier                        
                  isTrain: True                          	[default: None]
                lambda_L1: 100.0                         
                       lr: 0.001                         
          lr_decay_epochs: 100                           
           lr_decay_iters: 5000000                       
                 lr_gamma: 0.9                           
                lr_policy: lambda                        
         max_dataset_size: inf                           
                    model: DCCA_sparse                   
                 momentum: 0.9                           
                       nP: 500                           
                     name: experiment_name               
                    niter: 400                           
                  no_flip: True                          
                     norm: instance                      
              num_threads: 0                             
                    phase: train                         
               print_freq: 1                             
           resize_or_crop: none                          
          save_epoch_freq: 1                             
                     seed: 0                             
           serial_batches: False                         
                   suffix:                               
                test_path: D:/科研资料/CCA/CFCNet-master/nyudepthv2/val/
               train_path: D:/科研资料/CCA/CFCNet-master/nyudepthv2/train/
                  verbose: False                         
             weight_decay: 0.0005                        
----------------- End -------------------
#training images = 2974
#test images = 654
initialize network with xavier
initialize network with xavier
model [DCCASparseNetModel] was created
---------- Networks initialized -------------
[Network DCCASparseNet] Total number of parameters : 40.417 M
-----------------------------------------------
Traceback (most recent call last):
  File "D:/科研资料/CCA/CFCNet-master/train_depth_complete.py", line 72, in <module>
    nn = next(iterator)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\utils\data\_utils\collate.py", line 83, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\utils\data\_utils\collate.py", line 83, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "D:\Anaconda\envs\pytorch\lib\site-packages\torch\utils\data\_utils\collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [6, 224, 224] at entry 0 and [8, 224, 224] at entry 3

进程已结束，退出代码为 1

**Comment by choyingw** [comment]
From your error message, it seems that it stems from data preparation. 

I have updated this repository a little bit (adding a tutorial section). Please try the commands in the tutorial section and see if you can get anything output from the exemplar commands. If you still have issues, I'll to upload pre-processed data on my side.

**Comment by QiuJunning** [comment]
I'm sorry to bother you. I didn't run the program successfully. Please upload pre-processed data， thank you！

**Comment by choyingw** [comment]
Hi Please download the preprocessed data here https://github.com/fangchangma/sparse-to-dense (link at the requirements section). If there is any further issue, please let me know
